document.querySelectorAll(".js-current-date").forEach((e => {
	e.innerHTML = moment().format("DD.MM.YYYY")
})), document.querySelectorAll(".js-current-month").forEach((e => {
	e.innerHTML = moment().format("MMMM")
})), document.querySelectorAll(".js-current-year").forEach((e => {
	e.innerHTML = moment().format("YYYY")
})), document.querySelectorAll(".day-1").forEach((e => {
	e.innerHTML = moment().add(-1, "days").format("DD.MM.YYYY")
})), document.querySelectorAll(".day-2").forEach((e => {
	e.innerHTML = moment().add(-2, "days").format("DD.MM.YYYY")
})), document.querySelectorAll(".day-3").forEach((e => {
	e.innerHTML = moment().add(-3, "days").format("DD.MM.YYYY")
})), document.querySelectorAll(".day-4").forEach((e => {
	e.innerHTML = moment().add(-4, "days").format("DD.MM.YYYY")
})), document.querySelectorAll(".day-5").forEach((e => {
	e.innerHTML = moment().add(-5, "days").format("DD.MM.YYYY")
})), document.querySelectorAll(".day-6").forEach((e => {
	e.innerHTML = moment().add(-6, "days").format("DD.MM.YYYY")
}))